name: trustflow-app
region: nyc

services:
  - name: web
    github:
      repo: stampedehosting/30-Days-to-a-High-Trust-Life-
      branch: main
      deploy_on_push: true
    
    source_dir: /
    
    environment_slug: static
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    routes:
      - path: /
