name: trustflow-app
region: nyc

services:
  - name: web
    github:
      repo: stampedehosting/30-Days-to-a-High-Trust-Life-
      branch: main
      deploy_on_push: true
    
    source_dir: /next-app
    
    environment_slug: node-js
    
    build_command: npm install && npm run build
    
    run_command: npm start
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    routes:
      - path: /
